### ISSUE TITLE
Error when loading plugin if account is not linked

### ISSUE THREAD

**Issue by HawaiinYeti** [jimporter/giantbomb-kodi#18]
Was doing a bit of development work on a fresh install of Kodi and laziness caused me to try to load the plugin without linking my Giant Bomb account, which promptly errored out.

Kodi.log shows:
```
2019-03-20 20:05:13.536 T:123145420558336   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'video'
                                            Traceback (most recent call last):
                                              File "/Users/hawaiinyeti/Library/Application Support/Kodi/addons/plugin.video.giantbomb/default.py", line 485, in <module>
                                                handler.run(sys.argv[2])
                                              File "/Users/hawaiinyeti/Library/Application Support/Kodi/addons/plugin.video.giantbomb/resources/lib/requesthandler.py", line 60, in run
                                                self._default_mode_mapping(**params)
                                              File "/Users/hawaiinyeti/Library/Application Support/Kodi/addons/plugin.video.giantbomb/default.py", line 91, in index
                                                list_categories()
                                              File "/Users/hawaiinyeti/Library/Application Support/Kodi/addons/plugin.video.giantbomb/default.py", line 112, in list_categories
                                                if live_data['video'] is not None:
                                            KeyError: 'video'
                                            -->End of Python script error report<--
```

Looks like live_data doesn't have any data if an account isn't linked

**Comment by jimporter** [comment]
Resolved via #19
